language: python
python:
- '3.4'
- '3.5'
- '3.6'
virtual_env:
  system_site_packages: true
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script: pytest --cov=suds_requests
deploy:
  provider: pypi
  user: danimaribeiro
  password:
    secure: SUMU/mAG/ofULKS598pW7coNYAinf/99EggHht+S8JEYVJNI7tWJ5Pxp2X/BzF/dC8DXOIlC1GKgcI2PKUo3Y7Ih8naxOew0eT4/EQpug17xSwx/6pQ0FSawJgT23/x21nhSAJsek239lWlKY5Gs6NnicwyYqLWl0pwgiGUALtKMZws7WPPD1B8Xp9i6TaqniXGZ58Z+Y2AL02goVXTqzl4Nmzg7qsQOYMLUsNV/8cljnq4ykvHqWXEn3937eX0sLAPtHNXi1wNfWqjzSUqQpCh1gwhVZOk5rYsOwKCdMHJAtj0Uzz9gUYLeg1XikhI+BEufPmL6nBn4WbVYUBBlkaDBG1On1aOrLNAFLFYrQqeUF2w2KVoaUY6iUYAdwttVdRJ2zuvTaghlhePEI86+1EB6lwMpzo23Q03hBLMao+yPMonFIWbT/KCZKiPlDraoKfr/nnWbS9HbMECz4JnAQpWI/0avydCB7y5ZlsPLfMw2NrjobhcnunqevpG3G+XhqP04CSJ0qbWALVv2RZJuRAxIXMPLY3l6N8Nz94lgHUB/lXn3cEWgSkEKBRFwAIP+18j2MwuaucpXEH5Fwp8V9Ll4wk+0Z8V/wCTAf4KGRtDJf3R/h4VQ4+EmhGCW1s01MCx69Pk1LMq7Y3FtLXyJAeQ05hz4Pbj5OvJC05LVn+M=
  on:
    distributions: bdist_wheel
    repo: danimaribeiro/suds_requests
    branch: master
